### ISSUE TITLE
Add support for netstandard1.3 or netstandard2.0

### ISSUE THREAD

**Issue by jonjomckay** [fulviocanducci/Canducci.SqlKata.Dapper#1]
I just found this library and it looks perfect for us, however we're unable to use it as our class libraries are only targeting `netstandard1.3` (and some `netstandard2.0`). Would you be able to lower the target to one of those? It'll allow the library to be used in a few more projects - I'm happy to contribute too if needed!

**Comment by fulviocanducci** [comment]
Greetings !!!

I made the addition for `1.3` to `2.0` please check if it was compatible and can be used in the projects.

>![de1](https://user-images.githubusercontent.com/25593291/31772187-981ae0fc-b4bd-11e7-8f16-a6f45f0a2cc3.png)

### Note:

This package has as its main basis the SqlKata package responsible for generating the SQL but, which is still in the beta-353 version, I made a pull request request and so far there has been no return.

This package for this reason has some problems that I want to remove, but anti-hand it is almost ideal for use.

https://github.com/sqlkata/querybuilder/pull/22

Thanks for the contact.

**Comment by fulviocanducci** [comment]
@jonjomckay [Web Test Project with the 3 Bank Manager Systems.](https://github.com/fulviocanducci/Canducci.SqlKata.Database.Web)

**Comment by jonjomckay** [comment]
@fulviocanducci amazing, it works perfectly - thanks!! P.S. the `netstandard1.4;netstandard1.5;netstandard1.6` targets aren't needed if you're targeting `netstandard1.3` already, as they all inherit from it :)
