### ISSUE TITLE
Returning id's when insearting multiple

### ISSUE THREAD

**Issue by murillio4** [fulviocanducci/Canducci.SqlKata.Dapper#2]
The `SaveInsertAsync<T>()` only support `T` as struct. When inserting multiple with `returning id` you will get an array of integers back. int[] is not a struct. Is it possible to fix this?

**Comment by murillio4** [comment]
My workaround atm is extending the package and creating a function like  `await query.SaveInsertMultipleAsync<int>()`

**Comment by fulviocanducci** [comment]
> The `SaveInsertAsync<T>()` only support `T` as struct. When inserting multiple with `returning id` you will get an array of integers back. int[] is not a struct. Is it possible to fix this?


Do I need you to model in a code and say which database do you use?

**Comment by fulviocanducci** [comment]
> My workaround atm is extending the package and creating a function like `await query.SaveInsertMultipleAsync<int>()`

Checking for a possibility, please wait ...
